spring:
  application:
    name: Kafka Templated Data Producer
  main:
    web-application-type: NONE


settings:
  topic-name: output-topic
  message-count: 1
  message-interval: 1
  start-time: null
  message-template-file: ""
  template-config-file: ""
